#ifdef ODM_HQ_EDIT */
#/* zuoqiquan@ODM_HQ.Sensors.SCP.BSP, 2018/11/26,for sensors cts/vts fail  */
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/sensorHub/inc_v1
obj-y := sensor_list.o
#endif /* ODM_HQ_EDIT */